# Generated by Django 4.1.6 on 2023-03-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='base.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
