# Generated by Django 4.1.6 on 2023-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='technology',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='base.project'),
        ),
    ]
